apiVersion: v1
kind: Service
metadata:
  name: ocsapplication
spec:
  selector:
    app: ocsapplication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ocsdb
spec:
  selector:
    app: ocsdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: ocsproxy
spec:
  selector:
    app: ocsproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443

